#see https://www.topaz.sh/docs/deployment/docker-compose for instructions
version: "3.5"
services:
  topaz:
    command:
      - run
      - --config-file
      - /config/local.yaml
    container_name: topaz
    environment:
      - EAMERALD_POLICIES_DIR=/policies
      - EAMERALD_CERTS_DIR=/certs
      - EAMERALD_DB_DIR=/db
      - EAMERALD_DECISIONS_DIR=/decisions
      - ENTRA_TENANT_ID=${ENTRA_TENANT_ID}
      - ENTRA_CLIENT_ID=${ENTRA_CLIENT_ID}
      - ENTRA_CLIENT_SECRET=${ENTRA_CLIENT_SECRET}
    image: eamerald:local
    build:
      context: ../../..
      dockerfile: k8s/Dockerfile.dev
    ports:
      - 8080:8080 # console http
      - 8081:8081 # console grpc
      - 8282:8282 # authorizer grpc
      - 8383:8383 # authorizer http
      - 9292:9292 # directory grpc
      - 9393:9393 # directory http
      - 9494:9494 # healthcheck
      - 9696:9696 # metrics
    networks:
      - my-network
    volumes:
      - ./config:/config
      - ./policies:/policies
      - ./certs:/certs
      - ./db:/db
      - ./data:/data
      - ./decisions:/decisions
networks:
  my-network:
    driver: bridge
    name: my-network
