#!/usr/bin/env bash

#!/usr/bin/env bash

set -eu
set -o errexit
set -o nounset
set -o pipefail

# use the config settings from eamerald CLI
CONFIG_NAME=$(eamerald config info runtime.active_configuration_name --raw)
CONTAINER_NAME="eamerald-${CONFIG_NAME}"

echo "stop config ${CONFIG_NAME}"

docker stop ${CONTAINER_NAME}
